services:
  - type: web
    name: biz3120-trading-sim
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.1
      - key: PORT
        value: 8000
    plan: free