services:
  - type: web
    name: biz3120-trading-sim
    env: python
    python_version: 3.11.11  # Using the version Render installed
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python -m gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 8000
    plan: free